# -*- coding: utf-8 -*-
"""factorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5QTLP1v4--CbEgDZxEASYx52TEuMx5X

factorial
"""

n=5
fact=1
for i in range(1,n+1):
  fact=fact*i
print(fact)